version: "3"
services:
  shortLink:
    image: short_link
    container_name: short_link
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - app_net
    ports:
      - 80:8000

networks:
  app_net:
    external:
      name: app_net
